spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://users_db:3306/users_db
    username: users_user
    password: users_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: synchronization-broker
    port: 5672
    username: rabbitmq_user
    password: rabbitmq_pass

server:
  port: 8081

